/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me/diaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 日記一覧取得
         * @description 現在のユーザーの日記一覧を取得します
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Diary"][];
                        };
                    };
                };
                /** @description サーバーエラー */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 日記作成
         * @description 現在のユーザーの新しい日記を作成します
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateDiaryDTO"];
                };
            };
            responses: {
                /** @description 作成成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Diary"];
                        };
                    };
                };
                /** @description リクエストが不正 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 複合ユニークキー制約違反（同じユーザーの同じ日付の日記が既に存在） */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description サーバーエラー */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/diaries/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 日記取得
         * @description 現在のユーザーの指定された日付の日記を取得します
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 日付（YYYY-MM-DD形式） */
                    date: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Diary"];
                        };
                    };
                };
                /** @description リクエストが不正（無効な日付） */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 指定された日記が見つかりません */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description サーバーエラー */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        /**
         * 日記更新
         * @description 現在のユーザーの指定された日付の日記を更新します
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 日付（YYYY-MM-DD形式） */
                    date: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateDiaryDTO"];
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Diary"];
                        };
                    };
                };
                /** @description リクエストが不正 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 指定された日記が見つかりません */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description サーバーエラー */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        /**
         * 日記削除
         * @description 現在のユーザーの指定された日付の日記を削除します
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 日付（YYYY-MM-DD形式） */
                    date: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description 成功メッセージ
                             * @example 日記が正常に削除されました
                             */
                            message?: string;
                        };
                    };
                };
                /** @description リクエストが不正（無効な日付） */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 指定された日記が見つかりません */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description サーバーエラー */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Diary: {
            /** @description 日記ID */
            id: number;
            /** @description ユーザーID */
            user_id: number;
            /**
             * Format: date
             * @description 日付（YYYY-MM-DD形式）
             */
            date: string;
            /** @description メンタルスコア（1〜10の整数） */
            mental: number;
            /** @description 日記の内容 */
            diary: string;
        };
        /** @description メンタルスコア（1〜10の整数） */
        Mental: number;
        CreateDiaryDTO: {
            /**
             * Format: date
             * @description 日付（YYYY-MM-DD形式）
             */
            date: string;
            /** @description メンタルスコア（1〜10の整数） */
            mental: number;
            /** @description 日記の内容 */
            diary: string;
        };
        UpdateDiaryDTO: {
            /** @description メンタルスコア（1〜10の整数） */
            mental: number;
            /** @description 日記の内容 */
            diary: string;
        };
        Error: {
            /** @description エラーメッセージ */
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
